export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADD_STORY_GENRE_SUCCESS = "ADD_STORY_GENRE_SUCCESS";
export const ADD_STORY_GENRE_FAIL  = "ADD_STORY_GENRE_FAIL ";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";